language: scala

jdk:
  - oraclejdk8

scala:
  - 2.12.2

sudo: false

env:
   - TRAVIS_NODE_VERSION="5"

before_install:
   - nvm install node

install:
   - npm install jsdom

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

script:
  # Your normal script
  - sbt -J-XX:ReservedCodeCacheSize=256M +test

  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
